/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiaSlugRouteImport } from './routes/noticia/$slug'
import { Route as EditoriaCategoryRouteImport } from './routes/editoria/$category'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSlugRoute = NoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoriaCategoryRoute = EditoriaCategoryRouteImport.update({
  id: '/editoria/$category',
  path: '/editoria/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/busca': typeof BuscaRoute
  '/sobre': typeof SobreRoute
  '/editoria/$category': typeof EditoriaCategoryRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/busca': typeof BuscaRoute
  '/sobre': typeof SobreRoute
  '/editoria/$category': typeof EditoriaCategoryRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/busca': typeof BuscaRoute
  '/sobre': typeof SobreRoute
  '/editoria/$category': typeof EditoriaCategoryRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$' | '/busca' | '/sobre' | '/editoria/$category' | '/noticia/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/$' | '/busca' | '/sobre' | '/editoria/$category' | '/noticia/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/busca'
    | '/sobre'
    | '/editoria/$category'
    | '/noticia/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BuscaRoute: typeof BuscaRoute
  SobreRoute: typeof SobreRoute
  EditoriaCategoryRoute: typeof EditoriaCategoryRoute
  NoticiaSlugRoute: typeof NoticiaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$slug': {
      id: '/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof NoticiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editoria/$category': {
      id: '/editoria/$category'
      path: '/editoria/$category'
      fullPath: '/editoria/$category'
      preLoaderRoute: typeof EditoriaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BuscaRoute: BuscaRoute,
  SobreRoute: SobreRoute,
  EditoriaCategoryRoute: EditoriaCategoryRoute,
  NoticiaSlugRoute: NoticiaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
